name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "40 5 * * *" # every day at 5:40

# This causes PR pushes to cancel previous builds, but does not impact cron jobs due to use of .ref, which will have the commit.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - run: cargo --version --verbose
      - uses: Swatinem/rust-cache@v2
      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - name: "Run `cargo check`"
        run: cargo check --all-targets --all

  setup-features:
    name: "Setup bootloader feature matrix"
    runs-on: ubuntu-latest
    outputs:
      features: ${{ steps.output-features.outputs.features }}
      names: ${{ steps.output-features.outputs.names }}
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-feature --locked
      - name: List features
        run: cargo feature -i bootloader 
      - name: Generate feature matrix
        id: output-features
        run: |
          echo "features=$(
            cargo feature -i bootloader 2> /dev/null | # List the features in Cargo.toml, and redirect stderr to null
              grep "=" | # Filter down to only actual features (Not additional stuff cargo-feature outputs)
              grep -v "default" | # Remove the default feature
              sed -r 's/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g' | # Strip color output from cargo-feature, since it doesn't do this on it's own.
              cut -d ' ' -f1 | # Remove everything after the feature name
              jq -Rrsc 'split("\n") | map(select(length>0))' # Convert to json
          )" >> $GITHUB_OUTPUT
      - run: |
          echo "names=$(
            cargo test -- --list 2>&1 | # List all tests
            grep 'Running' |  # Get the file/test names
            sed 's/^[ \t]*//' |  # Strip leading whitespace
            cut -d ' ' -f2 | # get the test name
            grep 'tests/' | # only ones in tests
            cut -d '/' -f2 | # get the filename
            cut -d '.' -f1 | # remove the extension
            jq -Rrsc 'split("\n") | map(select(length>0))' # Convert to json
          )" >> $GITHUB_OUTPUT
  test-features:
    needs: setup-features
    name: "Run tests with '${{ matrix.feature }}' feature"
    strategy:
      fail-fast: false
      matrix:
        feature: ${{fromJSON(needs.setup-features.outputs.features)}}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - run: cargo --version --verbose
      - uses: Swatinem/rust-cache@v2

      # install QEMU
      - name: Install QEMU
        run: sudo apt update && sudo apt install qemu-system-x86

      - name: "Print QEMU Version"
        run: qemu-system-x86_64 --version

      - uses: r7kamura/rust-problem-matchers@v1.1.0

      - name: Run integration test for feature ${{ matrix.feature }}
        run: cargo test --no-default-features --features ${{ matrix.feature }}
      - name: Run doc test for feature ${{ matrix.feature }}
        run: cargo test --doc --no-default-features --features ${{ matrix.feature }}

  test-features-status:
    needs: 
      - test-features
      - test-with-matrix
    runs-on: ubuntu-latest
    name: "Tests pass"
    steps:
      - run: exit 0

  test-with-matrix:
    needs: setup-features
    name: "Run test suite '${{ matrix.test-name }}' on '${{ matrix.os }}'"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        test-name: ${{fromJSON(needs.setup-features.outputs.names)}}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - run: cargo --version --verbose
      - uses: Swatinem/rust-cache@v2
      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - name: Run api tests
        run: cargo test -p bootloader_api
      - name: Run document tests
        run: cargo test --doc
      # install QEMU
      - name: Install QEMU (Linux)
        run: sudo apt update && sudo apt install qemu-system-x86
        if: runner.os == 'Linux'
      - name: Install QEMU (macOS)
        run: brew install qemu
        if: runner.os == 'macOS'
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1
      - name: Install QEMU (Windows)
        run: |
          choco install qemu --version 2021.5.5
          echo "$Env:Programfiles\qemu" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        if: runner.os == 'Windows'
        shell: pwsh
      - name: "Print QEMU Version"
        run: qemu-system-x86_64 --version
      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - name: Run integration tests
        run: cargo test --test ${{ matrix.name }}

  fmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo --version --verbose
      - uses: Swatinem/rust-cache@v2
      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - run: cargo clippy --all --all-targets
